export default [
  'avon',
  'bedfordshire',
  'berkshire',
  'buckinghamshire',
  'cambridge',
  'cambridgeshire',
  'cheshire',
  'cleveland',
  'cornwall',
  'cumbria',
  'derbyshire',
  'devon',
  'dorset',
  'durham',
  'east sussex',
  'essex',
  'gloucestershire',
  'hampshire',
  'herefordshire',
  'hertfordshire',
  'isle of wight',
  'kent',
  'lancashire',
  'leicestershire',
  'lincolnshire',
  'london',
  'merseyside',
  'middlesex',
  'norfolk',
  'northamptonshire',
  'northumberland',
  'north humberside',
  'north yorkshire',
  'nottinghamshire',
  'oxfordshire',
  'rutland',
  'shropshire',
  'somerset',
  'south humberside',
  'south yorkshire',
  'staffordshire',
  'suffolk',
  'surrey',
  'tyne and wear',
  'warwickshire',
  'west midlands',
  'west sussex',
  'west yorkshire',
  'wiltshire',
  'worcestershire',
];
